### ISSUE TITLE
link in header leads to unexpected parsing

### ISSUE THREAD

**Issue by MatthewCaseres** [remarkjs/remark-slug#16] opened 2021-02-07 00:12 UTC
### Subject of the issue

I am trying to host the AWS docs on Next.js using MDX with the remark-slug plugin. The slug breaks when there is HTML in a header.

### Your environment

https://codesandbox.io/s/remark-debug-forked-9dggo?file=/src/index.js

### Expected behavior
I am expecting the slug to be consistent with how it is on GitHub.
### Actual behavior
I am getting id="sign-up-for-awsa-namesign-up-for-aws-gsga", but when viewed on  [GitHub](https://github.com/awsdocs/amazon-s3-getting-started-guide/blob/master/doc_source/SigningUpforS3.md#sign-up-for-aws)  the extension is #sign-up-for-aws.

**Comment by wooorm** [comment] 2021-02-10 08:26
Hi there! This is a duplicate of https://github.com/remarkjs/remark-slug/issues/11#issuecomment-556135965 I believe!

**Closed by wooorm** 2021-02-10 08:26 UTC
Labels: 🐛 type/bug, 🔍 status/open
